[versions]
kotlin = "2.1.20"
paper = "1.21.5-R0.1-SNAPSHOT"
jackson = "2.18.3"
mccoroutine = "2.22.0"
grpc = "1.71.0"
guice = "7.0.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ktfmt = "com.ncorti.ktfmt.gradle:0.21.0"
shadow = "com.gradleup.shadow:8.3.6"

[libraries]
# Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutine = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"

# Guice
guice = { module = "com.google.inject:guice", version.ref = "guice" }
guice-assistedinject = { module = "com.google.inject.extensions:guice-assistedinject", version.ref = "guice" }

# Jackson (yaml parsing, config validation, etc)
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson"}

# Paper and shaded dependencies
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
trove-client = "com.runicrealms.trove:trove-client:0.0.18-SNAPSHOT"
mccoroutine-api = { module = "com.github.shynixn.mccoroutine:mccoroutine-bukkit-api", version.ref = "mccoroutine" }
mccoroutine-core = { module = "com.github.shynixn.mccoroutine:mccoroutine-bukkit-core", version.ref = "mccoroutine" }
adventure-legacy = "net.kyori:adventure-text-serializer-legacy:4.21.0"
# gRPC/protobuf for Trove
grpc-kotlinstub = "io.grpc:grpc-kotlin-stub:1.4.1"
grpc-netty = { module = "io.grpc:grpc-netty", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
protobuf-java = "com.google.protobuf:protobuf-java:4.30.1"

# Plugin dependencies
velagones-paper = "com.runicrealms.velagones:velagones-paper:0.1.2"
nbtapi = "de.tr7zw:item-nbt-api-plugin:2.15.0"
protocollib = "com.comphenix.protocol:ProtocolLib:5.1.0"
